# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yuji SEKIYA Laboratory
email: sekiya@sekiya-lab.info
description: >- # this means to ignore newlines until "baseurl:"
  The University of Tokyo, Graduate School of Information Science and Technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sekiya-lab.info/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Theme settings
header_pages:
  - index.md
  - contacts.md
  - members.md
  - publications.md
  - relations.md
  - researches.md

page_navs:
  publications:
    - title: Journal
      id: journal
    - title: Book and Article
      id: book-and-article
    - title: International Conference
      id: international-conference
    - title: Domestic Conference
      id: domestic-conference
    - title: Master Thesis of Sekiya Lab. Graduates
      id: master-thesis-of-sekiya-lab-graduates
    - title: Internet-Draft
      id: internet-draft
    - title: Patent
      id: patent
    - title: Presentation
      id: presentation
    - title: Committee
      id: committee
    - title: Award
      id: award

home_cards:
  - title: Cloud Computing
    description: Cloud Computing is important services and technologies for recent IT infrastructures. We develop Cloud Controller for distributed IaaS Cloud and try to integrate resource management mechanism, distributed filesystem, and network migration using LISP and VXLAN technologies. The testbed is an inter-university IaaS cloud, called "WIDE Cloud".
    links:
      - title: WIDE Cloud
        url: https://wcc.wide.ad.jp/
        image: wide-cloud-logo.png
  - title: SDN and NFV
    description: Software Defined Network (SDN) is an important and hot keyword in DataCenter Network and Dedicated Network. We are working on effective management in DataCenter and Cloud Networks using OpenFlow from both of theoretical and practical approaches. Also, we establish the project for proof of concepts of Network Functions Virtualization (NFV). We evaluate and develop the elemental technologies architecture of NFV. 
    links:
      - title: NSP Consortium
        url: http://www.next-nsp.org/
        image: nsp-mini.png
      - title: GINEW
        url: http://www.ginew.net/
        image: ginew-logo-s.png
  - title: Cyber Security
    description: Cyber Security is important and imperative for the Internet. To against cyber attacks we join the EU-JP international collaboration, <a href="http://www.necoma-project.eu/" target="_blank">NECOMA Project</a>, of multi-layer resilient cyber-defence. In the project, we collect and analyze multi-layer datasets and develop resilient firewall. Also, DNSSEC is an important security mechanism to protect DNS queries from spoofing and attacking. We are developing DNSSEC simulator for accurate estimation of DNSSEC impacts.
    links:
      - title: NECOMA Project
        url: http://www.necoma-project.eu
        image: necoma-logo.png
      - title: DNSSEC Simulator Project
        url: https://dnssec.sekiya-lab.info
        image: l_033s.png

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
